### ISSUE TITLE
AWS Amplify Datastore snd Bloc

### ISSUE THREAD

**Issue by jobypthomas** [salihgueler/kahveinn_web#1]
Hello @salihgueler 
I have been using AWS Amplify for a while. I’m wondering what is the best practice about using AWS Datastore with Flutter Bloc? Appreciate your input.

Thanks!

**Comment by salihgueler** [comment]
Hello @jobypthomas,

Thank your for reaching out! 

Best practice to use Datastore with Bloc is to treat Datastore as any source of data and keep your architecture clean. We as AWS Amplify are working on some material to help you with that so stay tuned :)

**Comment by jobypthomas** [comment]
Thank you @salihgueler
I am currently using Datastore along with basic provider and now thinking of using Bloc. So, I am looking for some recommended architecture. Thank you for your help.
